GH-68: Add eslint and prettier to codefactor
gp-seattle/rms-app pull request #69
Opened 2021-07-21 18:44 UTC by jamestlee513

2021-07-21 18:57 UTC, yauj requested changes
Is there a way you can test this locally? And fix everything that needs to be fixed?

2021-07-21 18:57 UTC, yauj commented on .prettierrc
> +    "tabWidth": 2,
2 or 4?

2021-07-21 18:57 UTC, yauj commented on .prettierrc
> +    "printWidth": 80,
Hmmm. 100? Scared that 80 isn' wide enough.

2021-07-21 18:57 UTC, yauj commented on .prettierrc
> +    "useTabs": false,
Use tabs, not space. Technically saves space.

2021-07-21 18:57 UTC, yauj commented on .prettierrc
> +    "arrowParens": "avoid",
Can we do always? I personally prefer parenthesis, but we can fight on this one.

2021-07-24 16:38 UTC, yauj approved these changes

2021-08-03 04:15 UTC, DBarnes2 approved these changes

2021-08-03 04:16 UTC, merged